/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter-jobs'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CvRouteImport } from './routes/cv'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecruiterJobsJobIdRouteImport } from './routes/recruiter-jobs.$jobId'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/recruiter-jobs',
  path: '/recruiter-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsJobIdRoute = RecruiterJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => RecruiterJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/generator': typeof GeneratorRoute
  '/jobs': typeof JobsRoute
  '/linkedin': typeof LinkedinRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRoute
  '/recruiter-jobs': typeof RecruiterJobsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/recruiter-jobs/$jobId': typeof RecruiterJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/generator': typeof GeneratorRoute
  '/jobs': typeof JobsRoute
  '/linkedin': typeof LinkedinRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRoute
  '/recruiter-jobs': typeof RecruiterJobsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/recruiter-jobs/$jobId': typeof RecruiterJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/cv': typeof CvRoute
  '/dashboard': typeof DashboardRoute
  '/generator': typeof GeneratorRoute
  '/jobs': typeof JobsRoute
  '/linkedin': typeof LinkedinRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/recruiter': typeof RecruiterRoute
  '/recruiter-jobs': typeof RecruiterJobsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/recruiter-jobs/$jobId': typeof RecruiterJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/auth'
    | '/cv'
    | '/dashboard'
    | '/generator'
    | '/jobs'
    | '/linkedin'
    | '/messages'
    | '/profile'
    | '/recruiter'
    | '/recruiter-jobs'
    | '/skills'
    | '/recruiter-jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/auth'
    | '/cv'
    | '/dashboard'
    | '/generator'
    | '/jobs'
    | '/linkedin'
    | '/messages'
    | '/profile'
    | '/recruiter'
    | '/recruiter-jobs'
    | '/skills'
    | '/recruiter-jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/auth'
    | '/cv'
    | '/dashboard'
    | '/generator'
    | '/jobs'
    | '/linkedin'
    | '/messages'
    | '/profile'
    | '/recruiter'
    | '/recruiter-jobs'
    | '/skills'
    | '/recruiter-jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  CvRoute: typeof CvRoute
  DashboardRoute: typeof DashboardRoute
  GeneratorRoute: typeof GeneratorRoute
  JobsRoute: typeof JobsRoute
  LinkedinRoute: typeof LinkedinRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  RecruiterRoute: typeof RecruiterRoute
  RecruiterJobsRoute: typeof RecruiterJobsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-jobs': {
      id: '/recruiter-jobs'
      path: '/recruiter-jobs'
      fullPath: '/recruiter-jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-jobs/$jobId': {
      id: '/recruiter-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/recruiter-jobs/$jobId'
      preLoaderRoute: typeof RecruiterJobsJobIdRouteImport
      parentRoute: typeof RecruiterJobsRoute
    }
  }
}

interface RecruiterJobsRouteChildren {
  RecruiterJobsJobIdRoute: typeof RecruiterJobsJobIdRoute
}

const RecruiterJobsRouteChildren: RecruiterJobsRouteChildren = {
  RecruiterJobsJobIdRoute: RecruiterJobsJobIdRoute,
}

const RecruiterJobsRouteWithChildren = RecruiterJobsRoute._addFileChildren(
  RecruiterJobsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  CvRoute: CvRoute,
  DashboardRoute: DashboardRoute,
  GeneratorRoute: GeneratorRoute,
  JobsRoute: JobsRoute,
  LinkedinRoute: LinkedinRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  RecruiterRoute: RecruiterRoute,
  RecruiterJobsRoute: RecruiterJobsRouteWithChildren,
  SkillsRoute: SkillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
